In [1]:
import os
import pandas as pd

In [2]:
set_1 = pd.read_csv(os.path.abspath("../..") + "/bld/analysis/lpa_var_set_1_performance.csv")
set_2 = pd.read_csv(os.path.abspath("../..") + "/bld/analysis/lpa_var_set_2_performance.csv")
set_3 = pd.read_csv(os.path.abspath("../..") + "/bld/analysis/lpa_var_set_3_performance.csv")
set_4 = pd.read_csv(os.path.abspath("../..") + "/bld/analysis/lpa_var_set_4_performance.csv")

In [3]:
set_1.drop(set_1.columns[0], axis=1).round(2).sort_values(by=['BIC'])

,Model,Classes,LogLik,AIC,AWE,BIC,CAIC,CLC,KIC,SABIC,ICL,Entropy,prob_min,prob_max,n_min,n_max,BLRT_val,BLRT_p
4,1,5,-27544.39,55180.77,55978.93,55465.77,55511.77,55090.61,55229.77,55319.61,-56011.32,0.92,0.81,1.00,0.10,0.31,227.31,0.01
5,3,5,-28442.89,57019.78,58183.28,57434.89,57501.89,56887.50,57089.78,57222.00,-58129.44,0.86,0.56,1.00,0.03,0.55,648.84,0.01
3,3,4,-28701.28,57520.57,58544.97,57886.11,57945.11,57404.25,57582.57,57698.63,-58610.98,0.84,0.77,1.00,0.10,0.47,729.38,0.01
1,3,3,-29031.08,58164.17,59049.68,58480.14,58531.14,58063.61,58218.17,58318.09,-59600.57,0.72,0.79,0.91,0.10,0.66,843.18,0.01
2,1,4,-29694.48,59464.96,60124.14,59700.39,59738.39,59390.65,59505.96,59579.65,-60462.64,0.84,0.73,0.99,0.10,0.47,4296.86,0.01
0,1,3,-29810.85,59681.71,60201.60,59867.58,59897.58,59623.55,59714.71,59772.25,-60088.83,0.92,0.95,0.99,0.10,0.47,2109.78,0.01

In [15]:
a = (set_1.drop(set_1.columns[0], axis=1).round(2).sort_values(by=['BIC']))[['Model', 'Classes']].iloc[0].to_dict()
b = (set_3.drop(set_3.columns[0], axis=1).round(2).sort_values(by=['BIC']))[['Model', 'Classes']].iloc[0].to_dict()

fin = {
    "var_set_1": a,
    "var_set_3": b,
}
fin

{'var_set_1': {'Model': 1, 'Classes': 5},
 'var_set_3': {'Model': 3, 'Classes': 4}}

In [15]:
set_2.drop(set_2.columns[0], axis=1).round(2).sort_values(by=['BIC'])

,Model,Classes,LogLik,AIC,AWE,BIC,CAIC,CLC,KIC,SABIC,ICL,Entropy,prob_min,prob_max,n_min,n_max,BLRT_val,BLRT_p
4,1,5,-41132.30,82392.59,83503.79,82789.11,82853.11,82266.43,82459.59,82585.75,-83326.39,0.92,0.80,1.00,0.10,0.31,235.18,0.01
2,1,4,-41252.37,82610.74,83530.48,82939.11,82992.11,82506.74,82666.74,82770.70,-82939.13,1.00,1.00,1.00,0.10,0.43,4300.94,0.01
5,3,5,-41738.12,83694.25,85588.38,84369.57,84478.57,83477.76,83806.25,84023.22,-85820.61,0.76,0.70,0.98,0.02,0.48,3707.77,0.01
3,3,4,-41880.11,83956.22,85658.88,84563.39,84661.39,83761.90,84057.22,84252.00,-85277.38,0.84,0.78,1.00,0.10,0.47,218.60,0.01
1,3,3,-42175.64,84525.28,86036.67,85064.30,85151.30,84352.93,84615.28,84787.86,-85579.09,0.82,0.82,0.97,0.11,0.78,-6.84,0.98
0,1,3,-43402.92,86889.84,87618.44,87150.06,87192.06,86807.68,86934.84,87016.61,-87396.65,0.92,0.94,0.99,0.10,0.47,2157.56,0.01

In [16]:
set_3.drop(set_3.columns[0], axis=1).round(2).sort_values(by=['BIC'])

,Model,Classes,LogLik,AIC,AWE,BIC,CAIC,CLC,KIC,SABIC,ICL,Entropy,prob_min,prob_max,n_min,n_max,BLRT_val,BLRT_p
3,3,4,-55269.02,110830.04,113367.59,111734.60,111880.60,110539.61,110979.04,111270.68,-112733.89,0.78,0.81,0.95,0.09,0.52,-647.37,0.61
5,3,5,-55212.47,110744.93,113525.94,111736.23,111896.23,110426.52,110907.93,111227.83,-112839.89,0.79,0.68,0.95,0.04,0.51,677.15,0.01
1,3,3,-55867.35,111998.71,114292.76,112816.53,112948.53,111736.29,112133.71,112397.10,-113593.56,0.79,0.89,0.92,0.13,0.61,190.87,0.01
4,1,5,-57751.57,115667.15,117091.56,116175.19,116257.19,115504.82,115752.15,115914.63,-117103.67,0.84,0.80,0.97,0.09,0.30,3639.61,0.01
2,1,4,-58147.70,116431.39,117612.33,116852.69,116920.69,116297.06,116502.39,116636.62,-117675.92,0.83,0.88,0.97,0.09,0.33,2076.33,0.01
0,1,3,-59184.37,118476.75,119414.22,118811.31,118865.31,118370.40,118533.75,118639.73,-119517.49,0.83,0.91,0.93,0.19,0.48,2758.83,0.01

In [17]:
set_4.drop(set_4.columns[0], axis=1).round(2).sort_values(by=['BIC'])

,Model,Classes,LogLik,AIC,AWE,BIC,CAIC,CLC,KIC,SABIC,ICL,Entropy,prob_min,prob_max,n_min,n_max,BLRT_val,BLRT_p
4,1,5,-46703.58,93547.16,94762.59,93980.85,94050.85,93409.12,93620.16,93758.43,-94080.78,0.98,0.83,1.00,0.04,0.39,462.28,0.01
1,3,3,-46975.94,94153.88,95908.54,94779.63,94880.63,93953.72,94257.88,94458.71,-94988.52,0.92,0.81,0.99,0.07,0.72,963.54,0.01
5,3,5,-46891.16,94032.32,96204.91,94806.77,94931.77,93783.64,94160.32,94409.59,-96889.03,0.66,0.00,0.99,0.00,0.66,57.34,0.01
3,3,4,-46976.86,94179.72,96143.71,94879.82,94992.82,93954.93,94295.72,94520.76,-97560.48,0.61,0.60,0.99,0.07,0.38,254.51,0.01
2,1,4,-48796.27,97708.53,98715.52,98067.88,98125.88,97594.23,97769.53,97883.58,-98913.89,0.85,0.88,0.97,0.10,0.45,395.73,0.01
0,1,3,-48992.25,98076.51,98874.67,98361.50,98407.50,97986.34,98125.51,98215.34,-98611.99,0.92,0.94,0.99,0.10,0.47,2163.72,0.01